"""Начальная схема: клиенты, транзакции, анализ, история срабатываний, пользователи, журнал модели

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 08:22:18.726094
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import app.db

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('first_seen', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_events_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_base', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('recipient_id', sa.String(length=128), nullable=True),
    sa.Column('recipient_category', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('simulation_label', sa.Boolean(), nullable=True),
    sa.Column('simulation_anomaly_type', sa.String(length=64), nullable=True),
    sa.Column('received_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_transactions_client_ts', ['client_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_timestamp'), ['timestamp'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_pk', sa.Integer(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('deviation_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('model_kind', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('profile_updated', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_pk'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_pk')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_anomaly_score'), ['anomaly_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_status'), ['status'], unique=False)

    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_history_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_history_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_history_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_history_created_at'))
        batch_op.drop_index(batch_op.f('ix_alert_history_client_id'))
        batch_op.drop_index(batch_op.f('ix_alert_history_analysis_id'))

    op.drop_table('alert_history')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_analyses_risk_level'))
        batch_op.drop_index(batch_op.f('ix_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_analyses_anomaly_score'))

    op.drop_table('analyses')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_transactions_received_at'))
        batch_op.drop_index('ix_transactions_client_ts')
        batch_op.drop_index(batch_op.f('ix_transactions_client_id'))

    op.drop_table('transactions')
    op.drop_table('users')
    with op.batch_alter_table('model_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_events_created_at'))

    op.drop_table('model_events')
    op.drop_table('clients')
    # ### end Alembic commands ###
